name: Waka Readme

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.SAMPLE_SECRETS }}
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          SHOW_TOTAL: true
          SHOW_TIME: false
          
